// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4F9X30tQPhX7FnKGLkrJ7bBOP_wFzaQ',
    appId: '1:273969778163:web:22ebedb6ae7f92ed175686',
    messagingSenderId: '273969778163',
    projectId: 'first-58638',
    authDomain: 'first-58638.firebaseapp.com',
    storageBucket: 'first-58638.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXRRH0q39yHpCVOlPoBp_8I6zthm_4hc',
    appId: '1:273969778163:android:69210b7940088e23175686',
    messagingSenderId: '273969778163',
    projectId: 'first-58638',
    storageBucket: 'first-58638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmN0SQvzwMKaEVqUXS0oS7V9qMnX2d_E',
    appId: '1:273969778163:ios:9220b58e10defef9175686',
    messagingSenderId: '273969778163',
    projectId: 'first-58638',
    storageBucket: 'first-58638.appspot.com',
    iosBundleId: 'com.example.firrebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLmN0SQvzwMKaEVqUXS0oS7V9qMnX2d_E',
    appId: '1:273969778163:ios:11251a40bd95b83a175686',
    messagingSenderId: '273969778163',
    projectId: 'first-58638',
    storageBucket: 'first-58638.appspot.com',
    iosBundleId: 'com.example.firrebase.RunnerTests',
  );
}
